USE [master]
GO
/****** Object:  Database [dbSchool]    Script Date: 4/2/2025 5:07:24 AM ******/
CREATE DATABASE [dbSchool]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbSchool', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\dbSchool.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbSchool_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\dbSchool_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [dbSchool] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbSchool].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbSchool] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbSchool] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbSchool] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbSchool] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbSchool] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbSchool] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbSchool] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbSchool] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbSchool] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbSchool] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbSchool] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbSchool] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbSchool] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbSchool] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbSchool] SET  ENABLE_BROKER 
GO
ALTER DATABASE [dbSchool] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbSchool] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbSchool] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbSchool] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbSchool] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbSchool] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbSchool] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbSchool] SET RECOVERY FULL 
GO
ALTER DATABASE [dbSchool] SET  MULTI_USER 
GO
ALTER DATABASE [dbSchool] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbSchool] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dbSchool] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dbSchool] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dbSchool] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dbSchool] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbSchool', N'ON'
GO
ALTER DATABASE [dbSchool] SET QUERY_STORE = ON
GO
ALTER DATABASE [dbSchool] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [dbSchool]
GO
/****** Object:  UserDefinedFunction [dbo].[CalculateGPA164]    Script Date: 4/2/2025 5:07:24 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[CalculateGPA164](@StudentID INT)
RETURNS DECIMAL(3,2)
AS
BEGIN
    RETURN (
        SELECT AVG(CASE Grade
            WHEN 'A' THEN 4.0
            WHEN 'B' THEN 3.0
            WHEN 'C' THEN 2.0
            ELSE 0.0
        END)
        FROM GRADE164
        WHERE StudentID = @StudentID
    )
END;

GO
/****** Object:  Table [dbo].[Courses164]    Script Date: 4/2/2025 5:07:24 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Courses164](
	[CourseID] [int] IDENTITY(1,1) NOT NULL,
	[CourseName] [nvarchar](100) NOT NULL,
	[Credits] [int] NULL,
	[TeacherID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CourseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Enrollments164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Enrollments164](
	[EnrollmentID] [int] IDENTITY(1,1) NOT NULL,
	[StudentID] [int] NOT NULL,
	[CourseID] [int] NOT NULL,
	[EnrollmentDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[EnrollmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[StudentID] ASC,
	[CourseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grades164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grades164](
	[GradeID] [int] IDENTITY(1,1) NOT NULL,
	[StudentID] [int] NOT NULL,
	[CourseID] [int] NOT NULL,
	[Grade] [char](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[GradeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissions164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissions164](
	[PermissionID] [int] IDENTITY(1,1) NOT NULL,
	[PermissionName] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PermissionName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RolePermissions164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RolePermissions164](
	[RoleID] [int] NOT NULL,
	[PermissionID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC,
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles164](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[RoleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Students164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students164](
	[StudentID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Age] [int] NULL,
	[Gender] [nvarchar](10) NULL,
	[Address] [nvarchar](255) NULL,
	[PhoneNumber] [nvarchar](15) NULL,
	[EnrollmentDate] [date] NOT NULL,
	[UserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[StudentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Teachers164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teachers164](
	[TeacherID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Age] [int] NULL,
	[Gender] [nvarchar](10) NULL,
	[Department] [nvarchar](100) NULL,
	[PhoneNumber] [nvarchar](15) NULL,
	[UserID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TeacherID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users164](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[Role] [nvarchar](20) NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Enrollments164] ADD  DEFAULT (getdate()) FOR [EnrollmentDate]
GO
ALTER TABLE [dbo].[Students164] ADD  DEFAULT (getdate()) FOR [EnrollmentDate]
GO
ALTER TABLE [dbo].[Users164] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Courses164]  WITH CHECK ADD FOREIGN KEY([TeacherID])
REFERENCES [dbo].[Teachers164] ([TeacherID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Enrollments164]  WITH CHECK ADD FOREIGN KEY([CourseID])
REFERENCES [dbo].[Courses164] ([CourseID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Enrollments164]  WITH CHECK ADD FOREIGN KEY([StudentID])
REFERENCES [dbo].[Students164] ([StudentID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Grades164]  WITH CHECK ADD FOREIGN KEY([CourseID])
REFERENCES [dbo].[Courses164] ([CourseID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Grades164]  WITH CHECK ADD FOREIGN KEY([StudentID])
REFERENCES [dbo].[Students164] ([StudentID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RolePermissions164]  WITH CHECK ADD FOREIGN KEY([PermissionID])
REFERENCES [dbo].[Permissions164] ([PermissionID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RolePermissions164]  WITH CHECK ADD FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles164] ([RoleID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Students164]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Users164] ([UserID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Teachers164]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[Users164] ([UserID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Courses164]  WITH CHECK ADD CHECK  (([Credits]>(0)))
GO
ALTER TABLE [dbo].[Grades164]  WITH CHECK ADD CHECK  (([Grade]='F' OR [Grade]='E' OR [Grade]='D' OR [Grade]='C' OR [Grade]='B' OR [Grade]='A'))
GO
ALTER TABLE [dbo].[Students164]  WITH CHECK ADD CHECK  (([Gender]='Other' OR [Gender]='Female' OR [Gender]='Male'))
GO
ALTER TABLE [dbo].[Students164]  WITH CHECK ADD CHECK  (([Age]>(0)))
GO
ALTER TABLE [dbo].[Teachers164]  WITH CHECK ADD CHECK  (([Gender]='Other' OR [Gender]='Female' OR [Gender]='Male'))
GO
ALTER TABLE [dbo].[Teachers164]  WITH CHECK ADD CHECK  (([Age]>(0)))
GO
ALTER TABLE [dbo].[Users164]  WITH CHECK ADD CHECK  (([Role]='Guest' OR [Role]='Student' OR [Role]='Staff' OR [Role]='Admin'))
GO
/****** Object:  StoredProcedure [dbo].[BackupDatabase164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BackupDatabase164]
AS
BEGIN
    BACKUP DATABASE dbSCHOOL164
    TO DISK = 'C:\Backups\dbSCHOOL164.bak'
    WITH FORMAT, NAME = 'Full Backup of dbSCHOOL164';
END;

GO
/****** Object:  StoredProcedure [dbo].[CheckPermission164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[CheckPermission164]
    @Username VARCHAR(255),
    @PermissionName VARCHAR(255)
AS
BEGIN
    SELECT CASE WHEN EXISTS (
        SELECT 1
        FROM USER164 u
        JOIN ROLE_PERMISSION164 rp ON u.RoleID = rp.RoleID
        JOIN PERMISSION164 p ON rp.PermissionID = p.PermissionID
        WHERE u.Username = @Username
        AND p.PermissionName = @PermissionName
    ) THEN 1 ELSE 0 END AS HasPermission
END;


GO
/****** Object:  StoredProcedure [dbo].[EnrollStudent164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[EnrollStudent164]
    @StudentID INT,
    @CourseID INT
AS
BEGIN
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM ENROLLMENT164 
                   WHERE StudentID = @StudentID AND CourseID = @CourseID)
            RAISERROR('DUPLICATE_ENROLLMENT', 16, 1);
            
        INSERT INTO ENROLLMENT164 (StudentID, CourseID)
        VALUES (@StudentID, @CourseID);
        
        PRINT 'Enrollment successful!';
    END TRY
    BEGIN CATCH
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        IF @ErrorMessage = 'DUPLICATE_ENROLLMENT'
            RAISERROR('Student already enrolled in this course', 16, 1);
        ELSE
            RAISERROR('Enrollment failed', 16, 1);
    END CATCH
END;


GO
/****** Object:  StoredProcedure [dbo].[RestoreDatabase164]    Script Date: 4/2/2025 5:07:25 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[RestoreDatabase164]
AS
BEGIN
    RESTORE DATABASE dbSCHOOL164
    FROM DISK = 'C:\Backups\dbSCHOOL164.bak'
    WITH REPLACE;
END;

GO
USE [master]
GO
ALTER DATABASE [dbSchool] SET  READ_WRITE 
GO
